<?php

use App\Submarca;
use Illuminate\Database\Seeder;

class SubMarcasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Submarca::truncate();
		Submarca::create(['descripcion' => '500', 'marca_id' =>1]);
		Submarca::create(['descripcion' => 'Grande Punto', 'marca_id' =>1]);
		Submarca::create(['descripcion' => 'Punto Evo', 'marca_id' =>1]);
		Submarca::create(['descripcion' => '500c', 'marca_id' =>1]);
		Submarca::create(['descripcion' => '695', 'marca_id' =>1]);
		Submarca::create(['descripcion' => 'Punto', 'marca_id' =>1]);
		Submarca::create(['descripcion' => '155', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '156', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '159', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '164', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '145', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '147', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '146', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Gtv', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Spider', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '166', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Gt', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Crosswagon', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Brera', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '90', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '75', 'marca_id' =>2]);
		Submarca::create(['descripcion' => '33', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Giulietta', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Sprint', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Mito', 'marca_id' =>2]);
		Submarca::create(['descripcion' => 'Expander', 'marca_id' =>3]);
		Submarca::create(['descripcion' => '10', 'marca_id' =>3]);
		Submarca::create(['descripcion' => '24', 'marca_id' =>3]);
		Submarca::create(['descripcion' => 'Dacia', 'marca_id' =>3]);
		Submarca::create(['descripcion' => 'Rocsta', 'marca_id' =>4]);
		Submarca::create(['descripcion' => 'Rocsta', 'marca_id' =>5]);
		Submarca::create(['descripcion' => 'Db7', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'V8', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Db9', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Vanquish', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'V8 Vantage', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Vantage', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Dbs', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Volante', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Virage', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Vantage V8', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Vantage V12', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Rapide', 'marca_id' =>6]);
		Submarca::create(['descripcion' => 'Cygnet', 'marca_id' =>6]);
		Submarca::create(['descripcion' => '80', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A4', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A6', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S6', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Coupe', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S2', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Rs2', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A8', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Cabriolet', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S8', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A3', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S4', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Tt', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S3', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Allroad Quattro', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Rs4', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A2', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Rs6', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Q7', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'R8', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A5', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S5', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'V8', 'marca_id' =>7]);
		Submarca::create(['descripcion' => '200', 'marca_id' =>7]);
		Submarca::create(['descripcion' => '100', 'marca_id' =>7]);
		Submarca::create(['descripcion' => '90', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Tts', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Q5', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A4 Allroad Quattro', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Tt Rs', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Rs5', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A1', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A7', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Rs3', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Q3', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'A6 Allroad Quattro', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'S7', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Sq5', 'marca_id' =>7]);
		Submarca::create(['descripcion' => 'Mini', 'marca_id' =>8]);
		Submarca::create(['descripcion' => 'Montego', 'marca_id' =>8]);
		Submarca::create(['descripcion' => 'Maestro', 'marca_id' =>8]);
		Submarca::create(['descripcion' => 'Metro', 'marca_id' =>8]);
		Submarca::create(['descripcion' => 'Mini Moke', 'marca_id' =>8]);
		Submarca::create(['descripcion' => 'Diesel', 'marca_id' =>9]);
		Submarca::create(['descripcion' => 'Brooklands', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Turbo', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Continental', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Azure', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Arnage', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Continental Gt', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Continental Flying Spur', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Turbo R', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Mulsanne', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Eight', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Continental Gtc', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Continental Supersports', 'marca_id' =>10]);
		Submarca::create(['descripcion' => 'Freeclimber Diesel', 'marca_id' =>11]);
		Submarca::create(['descripcion' => 'Serie 3', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Serie 5', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Compact', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Serie 7', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Serie 8', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Z3', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Z4', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Z8', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'X5', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Serie 6', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'X3', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Serie 1', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Z1', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'X6', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'X1', 'marca_id' =>12]);
		Submarca::create(['descripcion' => 'Seville', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Sts', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'El Dorado', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Cts', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Xlr', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Srx', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Escalade', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Bls', 'marca_id' =>13]);
		Submarca::create(['descripcion' => 'Corvette', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Blazer', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Astro', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Nubira', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Evanda', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Trans Sport', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Camaro', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Matiz', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Alero', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Tahoe', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Tacuma', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Trailblazer', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Kalos', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Aveo', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Lacetti', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Epica', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Captiva', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Hhr', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Cruze', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Spark', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Orlando', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Volt', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Malibu', 'marca_id' =>14]);
		Submarca::create(['descripcion' => 'Vision', 'marca_id' =>15]);
		Submarca::create(['descripcion' => '300m', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Grand Voyager', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Viper', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Neon', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Voyager', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Stratus', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Sebring', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Sebring 200c', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'New Yorker', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Pt Cruiser', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Crossfire', 'marca_id' =>15]);
		Submarca::create(['descripcion' => '300c', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Le Baron', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Saratoga', 'marca_id' =>15]);
		Submarca::create(['descripcion' => 'Xantia', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Xm', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Ax', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Zx', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Evasion', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C8', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Saxo', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C2', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Xsara', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C4', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Xsara Picasso', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C5', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C3', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C3 Pluriel', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C1', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C6', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Grand C4 Picasso', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C4 Picasso', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Ccrosser', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C15', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Jumper', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Jumpy', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Berlingo', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Bx', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C25', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Cx', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Gsa', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Visa', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Lna', 'marca_id' =>16]);
		Submarca::create(['descripcion' => '2cv', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Nemo', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C4 Sedan', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Berlingo First', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C3 Picasso', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Ds3', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Czero', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Ds4', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Ds5', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'C4 Aircross', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Celysee', 'marca_id' =>16]);
		Submarca::create(['descripcion' => 'Corvette', 'marca_id' =>17]);
		Submarca::create(['descripcion' => 'Contac', 'marca_id' =>18]);
		Submarca::create(['descripcion' => 'Logan', 'marca_id' =>18]);
		Submarca::create(['descripcion' => 'Sandero', 'marca_id' =>18]);
		Submarca::create(['descripcion' => 'Duster', 'marca_id' =>18]);
		Submarca::create(['descripcion' => 'Lodgy', 'marca_id' =>18]);
		Submarca::create(['descripcion' => 'Nexia', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Aranos', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Lanos', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Nubira', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Compact', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Nubira Compact', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Leganza', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Evanda', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Matiz', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Tacuma', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Kalos', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Lacetti', 'marca_id' =>19]);
		Submarca::create(['descripcion' => 'Applause', 'marca_id' =>21]);
		Submarca::create(['descripcion' => 'Charade', 'marca_id' =>21]);
		Submarca::create(['descripcion' => 'Rocky', 'marca_id' =>21]);
		Submarca::create(['descripcion' => 'Feroza', 'marca_id' =>21]);
		Submarca::create(['descripcion' => 'Terios', 'marca_id' =>21]);
		Submarca::create(['descripcion' => 'Sirion', 'marca_id' =>21]);
		Submarca::create(['descripcion' => 'Serie Xj', 'marca_id' =>22]);
		Submarca::create(['descripcion' => 'Xj', 'marca_id' =>22]);
		Submarca::create(['descripcion' => 'Double Six', 'marca_id' =>22]);
		Submarca::create(['descripcion' => 'Six', 'marca_id' =>22]);
		Submarca::create(['descripcion' => 'Series Iii', 'marca_id' =>22]);
		Submarca::create(['descripcion' => 'Viper', 'marca_id' =>23]);
		Submarca::create(['descripcion' => 'Caliber', 'marca_id' =>23]);
		Submarca::create(['descripcion' => 'Nitro', 'marca_id' =>23]);
		Submarca::create(['descripcion' => 'Avenger', 'marca_id' =>23]);
		Submarca::create(['descripcion' => 'Journey', 'marca_id' =>23]);
		Submarca::create(['descripcion' => 'F355', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '360', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'F430', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'F512 M', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '550 Maranello', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '575m Maranello', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '599', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '456', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '456m', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '612', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'F50', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'Enzo', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'Superamerica', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '430', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '348', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'Testarossa', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '512', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '355', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'F40', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '412', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'Mondial', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '328', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'California', 'marca_id' =>24]);
		Submarca::create(['descripcion' => '458', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'Ff', 'marca_id' =>24]);
		Submarca::create(['descripcion' => 'Croma', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Cinquecento', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Seicento', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Punto', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Grande Punto', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Panda', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Tipo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Coupe', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Uno', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Ulysse', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Tempra', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Marea', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Barchetta', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Bravo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Stilo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Brava', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Palio Weekend', 'marca_id' =>25]);
		Submarca::create(['descripcion' => '600', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Multipla', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Idea', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Sedici', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Linea', 'marca_id' =>25]);
		Submarca::create(['descripcion' => '500', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Fiorino', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Ducato', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Doblo Cargo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Doblo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Strada', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Regata', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Talento', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Argenta', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Ritmo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Punto Classic', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Qubo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Punto Evo', 'marca_id' =>25]);
		Submarca::create(['descripcion' => '500c', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Freemont', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Panda Classic', 'marca_id' =>25]);
		Submarca::create(['descripcion' => '500l', 'marca_id' =>25]);
		Submarca::create(['descripcion' => 'Maverick', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Escort', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Focus', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Mondeo', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Scorpio', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Fiesta', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Probe', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Explorer', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Galaxy', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Ka', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Puma', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Cougar', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Focus Cmax', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Fusion', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Streetka', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Cmax', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Smax', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Transit', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Courier', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Ranger', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Sierra', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Orion', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Pick Up', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Capri', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Granada', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Kuga', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Grand Cmax', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Bmax', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Tourneo Custom', 'marca_id' =>26]);
		Submarca::create(['descripcion' => 'Exceed', 'marca_id' =>27]);
		Submarca::create(['descripcion' => 'Santamo', 'marca_id' =>27]);
		Submarca::create(['descripcion' => 'Super Exceed', 'marca_id' =>27]);
		Submarca::create(['descripcion' => 'Accord', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Civic', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Crx', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Prelude', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Nsx', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Legend', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Crv', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Hrv', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Logo', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'S2000', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Stream', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Jazz', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Frv', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Concerto', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Insight', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'Crz', 'marca_id' =>29]);
		Submarca::create(['descripcion' => 'H2', 'marca_id' =>30]);
		Submarca::create(['descripcion' => 'H3', 'marca_id' =>30]);
		Submarca::create(['descripcion' => 'H3t', 'marca_id' =>30]);
		Submarca::create(['descripcion' => 'Lantra', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Sonata', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Elantra', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Accent', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Scoupe', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Coupe', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Atos', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'H1', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Atos Prime', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Xg', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Trajet', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Santa Fe', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Terracan', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Matrix', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Getz', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Tucson', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'I30', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Pony', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Grandeur', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'I10', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'I800', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Sonata Fl', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Ix55', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'I20', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Ix35', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Ix20', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Genesis', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'I40', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'Veloster', 'marca_id' =>31]);
		Submarca::create(['descripcion' => 'G', 'marca_id' =>32]);
		Submarca::create(['descripcion' => 'Ex', 'marca_id' =>32]);
		Submarca::create(['descripcion' => 'Fx', 'marca_id' =>32]);
		Submarca::create(['descripcion' => 'M', 'marca_id' =>32]);
		Submarca::create(['descripcion' => 'Elba', 'marca_id' =>33]);
		Submarca::create(['descripcion' => 'Minitre', 'marca_id' =>33]);
		Submarca::create(['descripcion' => 'Trooper', 'marca_id' =>34]);
		Submarca::create(['descripcion' => 'Pick Up', 'marca_id' =>34]);
		Submarca::create(['descripcion' => 'D Max', 'marca_id' =>34]);
		Submarca::create(['descripcion' => 'Rodeo', 'marca_id' =>34]);
		Submarca::create(['descripcion' => 'Dmax', 'marca_id' =>34]);
		Submarca::create(['descripcion' => 'Trroper', 'marca_id' =>34]);
		Submarca::create(['descripcion' => 'Daily', 'marca_id' =>35]);
		Submarca::create(['descripcion' => 'Massif', 'marca_id' =>35]);
		Submarca::create(['descripcion' => 'Daily', 'marca_id' =>36]);
		Submarca::create(['descripcion' => 'Duty', 'marca_id' =>36]);
		Submarca::create(['descripcion' => 'Serie Xj', 'marca_id' =>37]);
		Submarca::create(['descripcion' => 'Serie Xk', 'marca_id' =>37]);
		Submarca::create(['descripcion' => 'Xj', 'marca_id' =>37]);
		Submarca::create(['descripcion' => 'Stype', 'marca_id' =>37]);
		Submarca::create(['descripcion' => 'Xf', 'marca_id' =>37]);
		Submarca::create(['descripcion' => 'Xtype', 'marca_id' =>37]);
		Submarca::create(['descripcion' => 'Wrangler', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Cherokee', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Grand Cherokee', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Commander', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Compass', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Wrangler Unlimited', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Patriot', 'marca_id' =>38]);
		Submarca::create(['descripcion' => 'Sportage', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Sephia', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Sephia Ii', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Pride', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Clarus', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Shuma', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Carnival', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Joice', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Magentis', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Carens', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Rio', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Cerato', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Sorento', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Opirus', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Picanto', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Ceed', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Ceed Sporty Wagon', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Proceed', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'K2500 Frontier', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'K2500', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Soul', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Venga', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Optima', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Ceed Sportswagon', 'marca_id' =>39]);
		Submarca::create(['descripcion' => 'Samara', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Niva', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Sagona', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Stawra 2110', 'marca_id' =>40]);
		Submarca::create(['descripcion' => '214', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Kalina', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Serie 2100', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Priora', 'marca_id' =>40]);
		Submarca::create(['descripcion' => 'Gallardo', 'marca_id' =>41]);
		Submarca::create(['descripcion' => 'Murcielago', 'marca_id' =>41]);
		Submarca::create(['descripcion' => 'Aventador', 'marca_id' =>41]);
		Submarca::create(['descripcion' => 'Delta', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'K', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Y10', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Dedra', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Lybra', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Z', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Y', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Ypsilon', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Thesis', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Phedra', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Musa', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Thema', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Zeta', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Kappa', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Trevi', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Prisma', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'A112', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Ypsilon Elefantino', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Voyager', 'marca_id' =>42]);
		Submarca::create(['descripcion' => 'Range Rover', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Defender', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Discovery', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Freelander', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Range Rover Sport', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Discovery 4', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Range Rover Evoque', 'marca_id' =>43]);
		Submarca::create(['descripcion' => 'Maxus', 'marca_id' =>44]);
		Submarca::create(['descripcion' => 'Ls400', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Ls430', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Gs300', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Is200', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Rx300', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Gs430', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Gs460', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Sc430', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Is300', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Is250', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Rx400h', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Is220d', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Rx350', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Gs450h', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Ls460', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Ls600h', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Ls', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Gs', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Is', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Sc', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Rx', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Ct', 'marca_id' =>45]);
		Submarca::create(['descripcion' => 'Elise', 'marca_id' =>46]);
		Submarca::create(['descripcion' => 'Exige', 'marca_id' =>46]);
		Submarca::create(['descripcion' => 'Bolero Pickup', 'marca_id' =>47]);
		Submarca::create(['descripcion' => 'Goa Pickup', 'marca_id' =>47]);
		Submarca::create(['descripcion' => 'Goa', 'marca_id' =>47]);
		Submarca::create(['descripcion' => 'Cj', 'marca_id' =>47]);
		Submarca::create(['descripcion' => 'Pikup', 'marca_id' =>47]);
		Submarca::create(['descripcion' => 'Thar', 'marca_id' =>47]);
		Submarca::create(['descripcion' => 'Ghibli', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Shamal', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Quattroporte', 'marca_id' =>48]);
		Submarca::create(['descripcion' => '3200 Gt', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Coupe', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Spyder', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Gransport', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Granturismo', 'marca_id' =>48]);
		Submarca::create(['descripcion' => '430', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Biturbo', 'marca_id' =>48]);
		Submarca::create(['descripcion' => '228', 'marca_id' =>48]);
		Submarca::create(['descripcion' => '224', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Grancabrio', 'marca_id' =>48]);
		Submarca::create(['descripcion' => 'Maybach', 'marca_id' =>49]);
		Submarca::create(['descripcion' => 'Xedos 6', 'marca_id' =>50]);
		Submarca::create(['descripcion' => '626', 'marca_id' =>50]);
		Submarca::create(['descripcion' => '121', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Xedos 9', 'marca_id' =>50]);
		Submarca::create(['descripcion' => '323', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mx3', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Rx7', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mx5', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mazda3', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mpv', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Demio', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Premacy', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Tribute', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mazda6', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mazda2', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Rx8', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mazda5', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Cx7', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Serie B', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'B2500', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Bt50', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Mx6', 'marca_id' =>50]);
		Submarca::create(['descripcion' => '929', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Cx5', 'marca_id' =>50]);
		Submarca::create(['descripcion' => 'Clase C', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase E', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Sl', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase S', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Cl', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase G', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Slk', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase V', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Viano', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Clk', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase A', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase M', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Vaneo', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Slklasse', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Slr Mclaren', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Cls', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase R', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Gl', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase B', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '100d', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '140d', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '180d', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Sprinter', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Vito', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Transporter', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '280', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '220', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '200', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '190', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '600', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '400', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Sl R129', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '300', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '500', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '420', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '260', 'marca_id' =>51]);
		Submarca::create(['descripcion' => '230', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Clc', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Clase Glk', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Sls Amg', 'marca_id' =>51]);
		Submarca::create(['descripcion' => 'Mgf', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Tf', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Zr', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Zs', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Zt', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Ztt', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Mini', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Countryman', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Paceman', 'marca_id' =>52]);
		Submarca::create(['descripcion' => 'Montero', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Galant', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Colt', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Space Wagon', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Space Runner', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Space Gear', 'marca_id' =>54]);
		Submarca::create(['descripcion' => '3000 Gt', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Carisma', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Eclipse', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Space Star', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Montero Sport', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Montero Io', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Outlander', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Lancer', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Grandis', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'L200', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Canter', 'marca_id' =>54]);
		Submarca::create(['descripcion' => '300 Gt', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Asx', 'marca_id' =>54]);
		Submarca::create(['descripcion' => 'Imiev', 'marca_id' =>54]);
		Submarca::create(['descripcion' => '44', 'marca_id' =>55]);
		Submarca::create(['descripcion' => 'Plus 8', 'marca_id' =>55]);
		Submarca::create(['descripcion' => 'Aero 8', 'marca_id' =>55]);
		Submarca::create(['descripcion' => 'V6', 'marca_id' =>55]);
		Submarca::create(['descripcion' => 'Roadster', 'marca_id' =>55]);
		Submarca::create(['descripcion' => '4', 'marca_id' =>55]);
		Submarca::create(['descripcion' => 'Plus 4', 'marca_id' =>55]);
		Submarca::create(['descripcion' => 'Terrano Ii', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Terrano', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Micra', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Sunny', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Primera', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Serena', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Patrol', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Maxima Qx', 'marca_id' =>56]);
		Submarca::create(['descripcion' => '200 Sx', 'marca_id' =>56]);
		Submarca::create(['descripcion' => '300 Zx', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Patrol Gr', 'marca_id' =>56]);
		Submarca::create(['descripcion' => '100 Nx', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Almera', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Pathfinder', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Almera Tino', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Xtrail', 'marca_id' =>56]);
		Submarca::create(['descripcion' => '350z', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Murano', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Note', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Qashqai', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Tiida', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Vanette', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Trade', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Vanette Cargo', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Pickup', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Navara', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Cabstar E', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Cabstar', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Maxima', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Camion', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Prairie', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Bluebird', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Np300 Pick Up', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Qashqai2', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Pixo', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Gtr', 'marca_id' =>56]);
		Submarca::create(['descripcion' => '370z', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Cube', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Juke', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Leaf', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Evalia', 'marca_id' =>56]);
		Submarca::create(['descripcion' => 'Astra', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Vectra', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Calibra', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Corsa', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Omega', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Frontera', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Tigra', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Monterey', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Sintra', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Zafira', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Agila', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Speedster', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Signum', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Meriva', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Antara', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Gt', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Combo', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Movano', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Vivaro', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Kadett', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Monza', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Senator', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Rekord', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Manta', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Ascona', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Insignia', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Zafira Tourer', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Ampera', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Mokka', 'marca_id' =>57]);
		Submarca::create(['descripcion' => 'Adam', 'marca_id' =>57]);
		Submarca::create(['descripcion' => '306', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '605', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '106', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '205', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '405', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '406', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '806', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '807', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '407', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '307', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '206', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '607', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '308', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '307 Sw', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '206 Sw', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '407 Sw', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '1007', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '107', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '207', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '4007', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Boxer', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Partner', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'J5', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '604', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '505', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '309', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Bipper', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Partner Origin', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '3008', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '5008', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Rcz', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '508', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Ion', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '208', 'marca_id' =>58]);
		Submarca::create(['descripcion' => '4008', 'marca_id' =>58]);
		Submarca::create(['descripcion' => 'Trans Sport', 'marca_id' =>59]);
		Submarca::create(['descripcion' => 'Firebird', 'marca_id' =>59]);
		Submarca::create(['descripcion' => 'Trans Am', 'marca_id' =>59]);
		Submarca::create(['descripcion' => '911', 'marca_id' =>60]);
		Submarca::create(['descripcion' => 'Boxster', 'marca_id' =>60]);
		Submarca::create(['descripcion' => 'Cayenne', 'marca_id' =>60]);
		Submarca::create(['descripcion' => 'Carrera Gt', 'marca_id' =>60]);
		Submarca::create(['descripcion' => 'Cayman', 'marca_id' =>60]);
		Submarca::create(['descripcion' => '928', 'marca_id' =>60]);
		Submarca::create(['descripcion' => '968', 'marca_id' =>60]);
		Submarca::create(['descripcion' => '944', 'marca_id' =>60]);
		Submarca::create(['descripcion' => '924', 'marca_id' =>60]);
		Submarca::create(['descripcion' => 'Panamera', 'marca_id' =>60]);
		Submarca::create(['descripcion' => '918', 'marca_id' =>60]);
		Submarca::create(['descripcion' => 'Megane', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Safrane', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Laguna', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Clio', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Twingo', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Nevada', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Espace', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Spider', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Scenic', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Grand Espace', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Avantime', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Vel Satis', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Grand Scenic', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Clio Campus', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Modus', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Express', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Trafic', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Master', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Kangoo', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Mascott', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Master Propulsion', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Maxity', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R19', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R25', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R5', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R21', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R4', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Alpine', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Fuego', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R18', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R11', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R9', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'R6', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Grand Modus', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Kangoo Combi', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Koleos', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Fluence', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Wind', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Latitude', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Grand Kangoo Combi', 'marca_id' =>61]);
		Submarca::create(['descripcion' => 'Siver Dawn', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Silver Spur', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Park Ward', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Silver Seraph', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Corniche', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Phantom', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Touring', 'marca_id' =>62]);
		Submarca::create(['descripcion' => 'Silvier', 'marca_id' =>62]);
		Submarca::create(['descripcion' => '800', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '600', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '100', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '200', 'marca_id' =>63]);
		Submarca::create(['descripcion' => 'Coupe', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '400', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '45', 'marca_id' =>63]);
		Submarca::create(['descripcion' => 'Cabriolet', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '25', 'marca_id' =>63]);
		Submarca::create(['descripcion' => 'Mini', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '75', 'marca_id' =>63]);
		Submarca::create(['descripcion' => 'Streetwise', 'marca_id' =>63]);
		Submarca::create(['descripcion' => 'Sd', 'marca_id' =>63]);
		Submarca::create(['descripcion' => '900', 'marca_id' =>64]);
		Submarca::create(['descripcion' => '93', 'marca_id' =>64]);
		Submarca::create(['descripcion' => '9000', 'marca_id' =>64]);
		Submarca::create(['descripcion' => '95', 'marca_id' =>64]);
		Submarca::create(['descripcion' => '93x', 'marca_id' =>64]);
		Submarca::create(['descripcion' => '94x', 'marca_id' =>64]);
		Submarca::create(['descripcion' => '300', 'marca_id' =>65]);
		Submarca::create(['descripcion' => '350', 'marca_id' =>65]);
		Submarca::create(['descripcion' => 'Anibal', 'marca_id' =>65]);
		Submarca::create(['descripcion' => 'Anibal Pick Up', 'marca_id' =>65]);
		Submarca::create(['descripcion' => 'Ibiza', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Cordoba', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Toledo', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Marbella', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Alhambra', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Arosa', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Leon', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Altea', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Altea Xl', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Altea Freetrack', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Terra', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Inca', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Malaga', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Ronda', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Exeo', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Mii', 'marca_id' =>66]);
		Submarca::create(['descripcion' => 'Felicia', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Forman', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Octavia', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Octavia Tour', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Fabia', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Superb', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Roomster', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Scout', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Pickup', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Favorit', 'marca_id' =>67]);
		Submarca::create(['descripcion' => '130', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'S', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Yeti', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Citigo', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Rapid', 'marca_id' =>67]);
		Submarca::create(['descripcion' => 'Smart', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Citycoupe', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Fortwo', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Cabrio', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Crossblade', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Roadster', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Forfour', 'marca_id' =>68]);
		Submarca::create(['descripcion' => 'Korando', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Family', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'K4d', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Musso', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Korando Kj', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Rexton', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Rexton Ii', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Rodius', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Kyron', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Actyon', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Sports Pick Up', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Actyon Sports Pick Up', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Kodando', 'marca_id' =>69]);
		Submarca::create(['descripcion' => 'Legacy', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Impreza', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Svx', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Justy', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Outback', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Forester', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'G3x Justy', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'B9 Tribeca', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Xt', 'marca_id' =>70]);
		Submarca::create(['descripcion' => '1800', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Tribeca', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Wrx Sti', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Trezia', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Xv', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Brz', 'marca_id' =>70]);
		Submarca::create(['descripcion' => 'Maruti', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Swift', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Vitara', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Baleno', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Samurai', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Alto', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Wagon R', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Jimny', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Grand Vitara', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Ignis', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Liana', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Grand Vitara Xl7', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Sx4', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Splash', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Kizashi', 'marca_id' =>71]);
		Submarca::create(['descripcion' => 'Samba', 'marca_id' =>72]);
		Submarca::create(['descripcion' => 'Tagora', 'marca_id' =>72]);
		Submarca::create(['descripcion' => 'Solara', 'marca_id' =>72]);
		Submarca::create(['descripcion' => 'Horizon', 'marca_id' =>72]);
		Submarca::create(['descripcion' => 'Telcosport', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Telco', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Sumo', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Safari', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Indica', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Indigo', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Grand Safari', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Tl Pick Up', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Xenon Pick Up', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Vista', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Xenon', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Aria', 'marca_id' =>73]);
		Submarca::create(['descripcion' => 'Carina E', 'marca_id' =>74]);
		Submarca::create(['descripcion' => '4runner', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Camry', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Rav4', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Celica', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Supra', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Paseo', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Land Cruiser 80', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Land Cruiser 100', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Land Cruiser', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Land Cruiser 90', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Corolla', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Auris', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Avensis', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Picnic', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Yaris', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Yaris Verso', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Mr2', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Previa', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Prius', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Avensis Verso', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Corolla Verso', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Corolla Sedan', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Aygo', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Hilux', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Dyna', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Land Cruiser 200', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Verso', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Iq', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Urban Cruiser', 'marca_id' =>74]);
		Submarca::create(['descripcion' => 'Gt86', 'marca_id' =>74]);
		Submarca::create(['descripcion' => '100', 'marca_id' =>75]);
		Submarca::create(['descripcion' => '121', 'marca_id' =>75]);
		Submarca::create(['descripcion' => '214', 'marca_id' =>76]);
		Submarca::create(['descripcion' => '110 Stawra', 'marca_id' =>76]);
		Submarca::create(['descripcion' => '111 Stawra', 'marca_id' =>76]);
		Submarca::create(['descripcion' => '215', 'marca_id' =>76]);
		Submarca::create(['descripcion' => '112 Stawra', 'marca_id' =>76]);
		Submarca::create(['descripcion' => 'Passat', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Golf', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Vento', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Polo', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Corrado', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Sharan', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Lupo', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Bora', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Jetta', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'New Beetle', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Phaeton', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Touareg', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Touran', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Multivan', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Caddy', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Golf Plus', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Fox', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Eos', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Caravelle', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Tiguan', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Transporter', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Lt', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Taro', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Crafter', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'California', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Santana', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Scirocco', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Passat Cc', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Amarok', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Beetle', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Up', 'marca_id' =>77]);
		Submarca::create(['descripcion' => 'Cc', 'marca_id' =>77]);
		Submarca::create(['descripcion' => '440', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '850', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'S70', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V70', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V70 Classic', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '940', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '480', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '460', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '960', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'S90', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V90', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'Classic', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'S40', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V40', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V50', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V70 Xc', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'Xc70', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'C70', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'S80', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'S60', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'Xc90', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'C30', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '780', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '760', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '740', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '240', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '360', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '340', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'Xc60', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V60', 'marca_id' =>78]);
		Submarca::create(['descripcion' => 'V40 Cross Country', 'marca_id' =>78]);
		Submarca::create(['descripcion' => '353', 'marca_id' =>79]);
		Submarca::create(['descripcion' => 'Mini', 'marca_id' =>53]);
		Submarca::create(['descripcion' => 'Countryman', 'marca_id' =>53]);
		Submarca::create(['descripcion' => 'Paceman', 'marca_id' =>53]);

	}
}
